### ISSUE TITLE
Server should be running on Port 78

### ISSUE THREAD

**Issue by monipan2817** [monipanny-org/DomainNameSystem#1]
We currently have a port clash and have agreed to move the server to port 78.

**Comment by monipan2817** [comment]
@quest-bot-dev stash 40

**Comment by monipan2817** [comment]
@quest-bot-dev reward @ornithos

**Comment by monipan2817** [comment]
@quest-bot-dev reward @monipan2817

**Comment by monipan2817** [comment]
@quest-bot-dev reward @monipan2817

**Comment by monipan2817** [comment]
@quest-bot-dev stash 100

**Comment by ornithos** [comment]
@quest-bot-dev stash 100
